version: "3.4"

services:
  caddy:
    build:
      context: ./
      target: caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-caddy-kubernetes-ingress-full-https-with-cloudflare.localhost}
      TLS_INTERNAL: ${TLS_INTERNAL:-tls internal}
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp

volumes:
  caddy_data:
  caddy_config:
